apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: taskapp

spec:

  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc

        imagePullPolicy: IfNotPresent

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        ports:

        - containerPort: 5000

        env:

        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URL

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SECRET_KEY

        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000

          initialDelaySeconds: 10

        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000

          initialDelaySeconds: 20