name: TaskApp CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/taskapp-backend
  IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/taskapp-frontend

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate manifests
        run: |
          kubeconform -summary -strict -ignore-missing-schemas manifests/*.yaml

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build skipped
        run: |
            echo "Using prebuilt images from GHCR."

  update-manifests:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Deployment handled by Argo CD
        run: |
          echo "GitOps repository already contains deployment manifests."